-- Seed activity categories — one INSERT per row to avoid SQL parser issues

-- PARENTS
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('sports','กีฬา','Sports','🏅',NULL,1) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('arts-music','ศิลปะและดนตรี','Arts & Music','🎨',NULL,2) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('outdoor','กิจกรรมกลางแจ้ง','Outdoor','🌲',NULL,3) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('hobbies','งานอดิเรก','Hobbies','🎯',NULL,4) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,sort_order=EXCLUDED.sort_order;

-- SPORTS
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('basketball','บาสเกตบอล','Basketball','🏀','sports',1) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('football','ฟุตบอล / ฟุตซอล','Football / Futsal','⚽','sports',2) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('volleyball','วอลเลย์บอล','Volleyball','🏐','sports',3) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('golf','กอล์ฟ','Golf','⛳','sports',4) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('badminton','แบดมินตัน','Badminton','🏸','sports',5) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('tennis','เทนนิส','Tennis','🎾','sports',6) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('table-tennis','ปิงปอง','Table Tennis','🏓','sports',7) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('swimming','ว่ายน้ำ','Swimming','🏊','sports',8) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('running','วิ่งมาราธอน / วิ่งสวน','Marathon / Jogging','🏃','sports',9) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('fitness','ฟิตเนส / เวทเทรนนิ่ง','Fitness / Weight Training','🏋','sports',10) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('yoga','โยคะ / พิลาทิส','Yoga / Pilates','🧘','sports',11) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('climbing','ปีนผาจำลอง','Rock Climbing','🧗','sports',12) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('cycling','ปั่นจักรยาน','Cycling','🚴','sports',13) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('martial-arts','มวยไทย / ศิลปะป้องกันตัว','Muay Thai / Martial Arts','🥊','sports',14) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('chess','หมากรุก','Chess','♟','sports',15) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('archery','ยิงธนู','Archery','🏹','sports',16) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('skydiving','กระโดดร่ม','Skydiving','🪂','sports',17) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('racing','แข่งรถ','Racing','🏎','sports',18) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('shooting','ยิงปืน','Shooting','🔫','sports',19) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('horse-riding','ขี่ม้า','Horse Riding','🏇','sports',20) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('ice-bath','แช่น้ำแข็ง','Ice Bath','🧊','sports',21) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('bowling','โบว์ลิ่ง','Bowling','🎳','sports',22) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('skateboarding','สเก็ตบอร์ด','Skateboarding','🛹','sports',23) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('surfing','เซิร์ฟ','Surfing','🏄','sports',24) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('skiing','สกี','Skiing','⛷','sports',25) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('rugby','รักบี้','Rugby','🏉','sports',26) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('judo','ยูโด','Judo','🥋','sports',27) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;

-- ARTS & MUSIC
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('dancing','เต้น','Dancing','💃','arts-music',1) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('guitar','เล่นกีตาร์','Guitar','🎸','arts-music',2) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('piano','เล่นเปียโน','Piano','🎹','arts-music',3) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('bass-drums','เล่นเบส / กลอง','Bass / Drums','🥁','arts-music',4) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('singing','ร้องเพลง','Singing','🎤','arts-music',5) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('music-production','ทำเพลง / โปรดิวซ์','Music Production','🎧','arts-music',6) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('painting','วาดรูป / ระบายสี','Painting / Drawing','🖌','arts-music',7) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('acting','การแสดง / ละคร','Acting / Theater','🎭','arts-music',8) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('writing','เขียนหนังสือ / นิยาย','Writing / Novels','✍','arts-music',9) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('pottery','ปั้นเซรามิก','Pottery / Ceramics','🏺','arts-music',10) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;

-- OUTDOOR
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('hiking','เดินป่า','Hiking','🥾','outdoor',1) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('camping','แคมป์ปิ้ง','Camping','⛺','outdoor',2) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('mountain-climbing','ปีนเขา','Mountain Climbing','🏔','outdoor',3) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('diving','ทะเล / ดำน้ำ','Sea / Diving','🤿','outdoor',4) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('fishing','ตกปลา','Fishing','🎣','outdoor',5) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('kayaking','พายเรือ / คายัค','Kayaking / Canoeing','🛶','outdoor',6) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('birdwatching','ส่องนก / ดูธรรมชาติ','Birdwatching / Nature','🦜','outdoor',7) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;

-- HOBBIES
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('cooking','ทำอาหาร','Cooking','🍳','hobbies',1) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('photography','ถ่ายรูป','Photography','📷','hobbies',2) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('reading','อ่านหนังสือ','Reading','📚','hobbies',3) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('meditation','สมาธิ','Meditation','🧠','hobbies',4) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('merit-making','ทำบุญ','Merit Making','🙏','hobbies',5) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('gaming','เล่นเกม','Gaming','🎮','hobbies',6) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('board-game','บอร์ดเกม','Board Games','🎲','hobbies',7) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('card-game','เกมการ์ด','Card Games','🃏','hobbies',8) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('coding','เขียนโค้ด','Coding','💻','hobbies',9) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('gardening','ปลูกต้นไม้ / จัดสวน','Gardening','🌱','hobbies',10) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('movies','ดูหนัง / ซีรีส์','Movies / Series','🎬','hobbies',11) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('karaoke','คาราโอเกะ','Karaoke','🎤','hobbies',12) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('traveling','ท่องเที่ยว','Traveling','✈','hobbies',13) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('language-learning','เรียนภาษา','Language Learning','📝','hobbies',14) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('crafts','งานฝีมือ / DIY','Crafts / DIY','🧵','hobbies',15) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('cafe-hopping','คาเฟ่ฮอปปิ้ง','Cafe Hopping','☕','hobbies',16) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('drinking','ดื่ม','Drinking','🍻','hobbies',17) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
INSERT INTO activity_categories (key,label_th,label_en,emoji,parent_key,sort_order) VALUES ('party','ปาร์ตี้','Party','🎉','hobbies',18) ON CONFLICT (key) DO UPDATE SET label_th=EXCLUDED.label_th,label_en=EXCLUDED.label_en,emoji=EXCLUDED.emoji,parent_key=EXCLUDED.parent_key,sort_order=EXCLUDED.sort_order;
