// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exjeqvboxyacmtzclnxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4amVxdmJveHlhY210emNsbnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMTAzNjUsImV4cCI6MjA4NDc4NjM2NX0.HdYoQxUqN083aXJhKyQH4tGW3sYQFFjCEiDUPLeb-bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});